version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    env_file:
    - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
