openapi: 3.0.3
info:
  title: Event Management API
  description: API for managing events, attendees, and related operations.
  version: 1.0.0
  contact:
    name: Jackson Mosquera
    email: snaft.j1@gmail.com
    url: www.coordinadora.com
servers:
  - url: http://localhost:3000/api/v1
    description: Local Development Server
  - url: https://api.coordinadora.com/v1
    description: Production Server

tags:
  - name: Events
    description: Operations related to events
  - name: Attendees
    description: Operations related to attendees

paths:
  /events:
    get:
      tags:
        - Events
      summary: Get all events
      responses:
        '200':
          description: A list of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '500':
          description: Internal server error

    post:
      tags:
        - Events
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewEvent'
      responses:
        '201':
          description: Event created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /events/{id}:
    get:
      tags:
        - Events
      summary: Get an event by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Event data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          description: Event not found
        '500':
          description: Internal server error

    put:
      tags:
        - Events
      summary: Update an event
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewEvent'
      responses:
        '200':
          description: Event updated successfully
        '400':
          description: Bad request
        '404':
          description: Event not found
        '500':
          description: Internal server error

    delete:
      tags:
        - Events
      summary: Delete an event
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Event deleted successfully
        '404':
          description: Event not found
        '500':
          description: Internal server error

components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: string
          example: "123e4567-e89b-12d3-a456-426614174000"
        name:
          type: string
          example: "Event Name"
        description:
          type: string
          example: "A detailed description of the event."
        date:
          type: string
          format: date-time
          example: "2024-12-31T23:59:59Z"
        location:
          type: string
          example: "123 Event Street, City, Country"
        organizerId:
          type: string
          example: "456e7890-e12b-34d5-f678-910111213141"

    NewEvent:
      type: object
      required:
        - name
        - date
        - location
        - organizerId
      properties:
        name:
          type: string
          example: "New Event Name"
        description:
          type: string
          example: "A detailed description of the event."
        date:
          type: string
          format: date-time
          example: "2024-12-31T23:59:59Z"
        location:
          type: string
          example: "123 Event Street, City, Country"
        organizerId:
          type: string
          example: "456e7890-e12b-34d5-f678-910111213141"